#!/usr/bin/env bash
# cluster/render-cluster-nodes.sh — build [cluster_nodes] and [ips_fixed] for
# every node, from the live pubkey_node of every OTHER node.
#
# Reads inventory.yml, asks each running node for its pubkey_node, and writes
# one fragment pair per node into cluster/rendered/. config/render-config.sh
# splices those into each node's xahaud.cfg.
#
# Adding node 3 = add it to inventory.yml, re-run this, re-render, rolling
# restart. Phase 1 clusters two nodes; the mechanism is identical for three.
#
# What clustering buys here: shared load and fee-escalation state, shared
# client abuse accounting, and transactions relayed between members skip
# redundant signature verification. Behind a load balancer that matters — a
# client cannot hop backends to dodge rate limiting. It has NO effect on
# consensus or trust; that is the UNL, and these are stock nodes.
#
# Usage:
#   cluster/render-cluster-nodes.sh                 # fragments only
#   cluster/render-cluster-nodes.sh --deploy        # + render + rolling restart
#   cluster/render-cluster-nodes.sh --cached        # reuse last known pubkeys
set -Eeuo pipefail
. "$(dirname "$(readlink -f "$0")")/../lib/common.sh"
. "$REPO_ROOT/lib/rpc.sh"
load_secrets

DEPLOY=0; CACHED=0; HISTORY=initial
while [ $# -gt 0 ]; do
  case "$1" in
    --deploy)  DEPLOY=1; shift ;;
    --cached)  CACHED=1; shift ;;
    --history) HISTORY="$2"; shift 2 ;;
    -h|--help) sed -n '2,/^set -E/p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
    *) die "unknown argument: $1" ;;
  esac
done

OUT="$REPO_ROOT/cluster/rendered"
KEYS="$OUT/pubkeys.tsv"
mkdir -p "$OUT"

mapfile -t NODES < <("$INV" nodes --enabled)
[ "${#NODES[@]}" -ge 1 ] || die "no enabled nodes in inventory.yml"
PEER_PORT="$("$INV" get cluster.ports.peer)"

hdr "collecting pubkey_node from ${#NODES[@]} node(s)"
declare -A PUB=() ADDR=()
if [ "$CACHED" = 1 ] && [ -f "$KEYS" ]; then
  while IFS=$'\t' read -r n k _; do PUB["$n"]="$k"; done < "$KEYS"
  warn "--cached: reusing $KEYS. A stale key means that node is silently NOT clustered."
fi

MISSING=()
for n in "${NODES[@]}"; do
  guard_reject_target "$n"
  ADDR["$n"]="$("$INV" node "$n" address)"
  if [ -n "${PUB[$n]:-}" ]; then
    printf '  %-14s %s (cached)\n' "$n" "${PUB[$n]}"
    continue
  fi
  k="$(node_pubkey "$n" 2>/dev/null || true)"
  if [ -n "$k" ]; then
    PUB["$n"]="$k"
    printf '  %-14s %s\n' "$n" "$k"
  else
    MISSING+=("$n")
    warn "$n: could not read pubkey_node (not running yet, or unreachable)"
  fi
done

if [ "${#MISSING[@]}" -gt 0 ]; then
  warn "missing pubkeys for: ${MISSING[*]}"
  warn "Those nodes will be OMITTED from every other node's [cluster_nodes]."
  warn "Clustering is symmetric — an omitted node is not clustered at all. Start it and re-run."
  [ "${#PUB[@]}" -ge 2 ] || die "fewer than two known pubkeys — nothing to cluster yet. Start the nodes first."
  confirm "Write fragments without ${MISSING[*]}?"
fi

# persist for --cached and for docs/backup
{ for n in "${!PUB[@]}"; do printf '%s\t%s\t%s\n' "$n" "${PUB[$n]}" "${ADDR[$n]}"; done; } | sort > "$KEYS"
ok "recorded $(wc -l < "$KEYS") pubkey(s) in cluster/rendered/pubkeys.tsv"

# ── detect a duplicated identity, which is the failure this repo guards ──────
DUPES="$(awk -F'\t' '{print $2}' "$KEYS" | sort | uniq -d)"
if [ -n "$DUPES" ]; then
  err "TWO NODES REPORT THE SAME pubkey_node:"
  grep -F "$DUPES" "$KEYS" >&2
  die "That is one identity on two nodes — almost always a copied node_seed. Mint a fresh seed (ops/gen-seed.sh --for NODE --append), re-render, redeploy. Do not cluster them like this."
fi

# ── write per-node fragments ────────────────────────────────────────────────
hdr "writing fragments"
for n in "${NODES[@]}"; do
  cn="$OUT/${n}.cluster-nodes.cfg"
  ip="$OUT/${n}.ips-fixed.cfg"
  {
    echo "# GENERATED by cluster/render-cluster-nodes.sh on $(date -u +%FT%TZ). Do not hand-edit."
    echo "# Every OTHER enabled node, by its live pubkey_node."
    echo "[cluster_nodes]"
    for m in "${NODES[@]}"; do
      [ "$m" = "$n" ] && continue
      [ -n "${PUB[$m]:-}" ] || continue
      printf '%s  %s\n' "${PUB[$m]}" "$m"
    done
  } > "$cn"
  {
    echo "# GENERATED by cluster/render-cluster-nodes.sh on $(date -u +%FT%TZ). Do not hand-edit."
    echo "# Peer addresses of the other cluster members, so they find each other"
    echo "# directly instead of relying on the public peer discovery."
    echo "[ips_fixed]"
    for m in "${NODES[@]}"; do
      [ "$m" = "$n" ] && continue
      [ -n "${PUB[$m]:-}" ] || continue
      printf '%s %s\n' "${ADDR[$m]}" "$PEER_PORT"
    done
  } > "$ip"
  peers="$(grep -c '^n' "$cn" || true)"
  printf '  %-14s %s peer(s)\n' "$n" "$peers"
  [ "$peers" = 0 ] && warn "$n has no cluster peers in its fragment — it will run unclustered"
done
ok "fragments written to cluster/rendered/"

if [ "$DEPLOY" = 0 ]; then
  hdr "next"
  cat >&2 <<'NEXT'
  make render         # splice the fragments into each node's xahaud.cfg
  make deploy-all     # rolling restart, one node at a time
  or do both:  cluster/render-cluster-nodes.sh --deploy
NEXT
  exit 0
fi

# ── render + rolling restart ────────────────────────────────────────────────
hdr "rendering configs"
"$REPO_ROOT/config/render-config.sh" --all --history "$HISTORY"

hdr "rolling restart — one node at a time so the endpoint stays up"
for n in "${NODES[@]}"; do
  info "── $n"
  "$REPO_ROOT/ops/deploy-node.sh" "$n" --restart --wait \
    || die "deploy to $n failed — STOPPING the rolling restart here so the remaining nodes keep serving. Fix $n, then re-run."
done
ok "cluster deployed"
"$REPO_ROOT/ops/healthcheck.sh" || true
