#!/usr/bin/env bash
# config/render-config.sh — render xahaud.cfg for a node from inventory + role
#                           + cluster fragments + the seed in secrets/.
#
# Usage:
#   config/render-config.sh NODE [options]
#   config/render-config.sh --all [options]
#
# Options:
#   --history initial|final   which ledger_history to use (default: initial)
#                             `initial` is the low measurement window;
#                             `final` is the target, allowed only once
#                             docs/DECISIONS.md records a measured GB/million.
#   --out DIR                 output dir (default: out/<node>)
#   --print                   write to stdout with the seed REDACTED
#   --no-seed                 render with a placeholder seed (for review/diff)
#
# Output is mode 0600 and gitignored. It contains a real node_seed.
set -Eeuo pipefail
. "$(dirname "$(readlink -f "$0")")/../lib/common.sh"

HISTORY=initial
OUTDIR=""
PRINT=0
NOSEED=0
NODES=()

while [ $# -gt 0 ]; do
  case "$1" in
    --all)      mapfile -t NODES < <("$INV" nodes --enabled); shift ;;
    --history)  HISTORY="$2"; shift 2 ;;
    --out)      OUTDIR="$2"; shift 2 ;;
    --print)    PRINT=1; shift ;;
    --no-seed)  NOSEED=1; shift ;;
    -h|--help)  sed -n '2,/^set -E/p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
    -*)         die "unknown option: $1" ;;
    *)          NODES+=("$1"); shift ;;
  esac
done
[ "${#NODES[@]}" -gt 0 ] || die "no node given. Use a node name or --all."

case "$HISTORY" in
  initial|final) : ;;
  *) die "--history must be 'initial' or 'final'" ;;
esac

render_one() {
  local node="$1"
  guard_reject_target "$node"

  # ── pull every value for this node (defaults + ports + role + node) ───────
  local kv; kv="$("$INV" node "$node")"
  local V_NAME V_VMID V_ROLE
  # shellcheck disable=SC2046
  eval "$kv"
  V_NAME="$N_NAME"; V_VMID="$N_VMID"; V_ROLE="$N_ROLE"
  guard_vmid "$V_VMID"

  # ── ledger_history selection ─────────────────────────────────────────────
  local lh
  if [ "$HISTORY" = final ]; then
    lh="$N_LEDGER_HISTORY"
    if ! grep -qi 'GB per million ledgers' "$REPO_ROOT/docs/DECISIONS.md" 2>/dev/null \
       || grep -qi 'MEASUREMENT PENDING' "$REPO_ROOT/docs/DECISIONS.md" 2>/dev/null; then
      warn "--history final requested but docs/DECISIONS.md still says MEASUREMENT PENDING."
      warn "Run ops/measure.sh on $node first and record GB-per-million-ledgers."
      confirm "Render $node with ledger_history=$lh anyway?"
    fi
  else
    lh="$N_LEDGER_HISTORY_INITIAL"
  fi

  # ── invariant: ledger_history < online_delete ────────────────────────────
  [ "$lh" -lt "$N_ONLINE_DELETE" ] \
    || die "$node: ledger_history ($lh) must be < online_delete ($N_ONLINE_DELETE) — otherwise the node fetches history only to delete it again. Fix config/roles/${V_ROLE}.yml."

  # ── seed ─────────────────────────────────────────────────────────────────
  local seed
  if [ "$NOSEED" = 1 ]; then
    seed="REPLACE_ME_UNIQUE_SEED_PER_NODE"
  else
    seed="$(require_seed "$N_SEED_VAR")"
  fi

  # ── cluster fragments (regenerated by cluster/render-cluster-nodes.sh) ───
  local frag="$REPO_ROOT/cluster/rendered/${node}.cluster-nodes.cfg"
  local ipsf="$REPO_ROOT/cluster/rendered/${node}.ips-fixed.cfg"
  local cn_block ips_block
  if [ -f "$frag" ]; then
    cn_block="$(cat "$frag")"
  else
    cn_block="# [cluster_nodes] not yet generated — run: make cluster
# (needs every peer node running so its pubkey_node can be read)"
  fi
  if [ -f "$ipsf" ]; then
    ips_block="$(cat "$ipsf")"
  else
    ips_block="# [ips_fixed] not yet generated — run: make cluster"
  fi

  # ── render ───────────────────────────────────────────────────────────────
  local dest="${OUTDIR:-$REPO_ROOT/out/$node}"
  mkdir -p "$dest"; chmod 700 "$dest"
  local tmp; tmp="$(mktemp)"; chmod 600 "$tmp"

  "$REPO_ROOT/lib/render.py" "$REPO_ROOT/config/xahaud.cfg.j2" \
    "node_name=$V_NAME" \
    "vmid=$V_VMID" \
    "role=$V_ROLE" \
    "network=$("$INV" get cluster.network)" \
    "network_id=$N_NETWORK_ID" \
    "port_rpc_admin=$N_RPC_ADMIN" \
    "port_peer=$N_PEER" \
    "port_ws_public=$N_WS_PUBLIC" \
    "port_rpc_public=$N_RPC_PUBLIC" \
    "db_mount=$N_DB_MOUNT" \
    "db_label=$N_DB_LABEL" \
    "online_delete=$N_ONLINE_DELETE" \
    "advisory_delete=$N_ADVISORY_DELETE" \
    "ledger_history=$lh" \
    "node_size=$N_NODE_SIZE" \
    "peers_max=$N_PEERS_MAX" \
    "sqlite_page_size=$N_SQLITE_PAGE_SIZE" \
    "sqlite_journal_mode=$N_SQLITE_JOURNAL_MODE" \
    "sqlite_synchronous=$N_SQLITE_SYNCHRONOUS" \
    "sqlite_temp_store=$N_SQLITE_TEMP_STORE" \
    "use_tx_tables=$N_USE_TX_TABLES" \
    "log_level=${XAH_LOG_LEVEL:-warning}" \
    "node_seed=$seed" \
    "cluster_nodes_block=$cn_block" \
    "ips_fixed_block=$ips_block" \
    "rendered_at=$(date -u '+%Y-%m-%dT%H:%M:%SZ')" \
    "template_name=config/xahaud.cfg.j2" \
    "repo=$(git -C "$REPO_ROOT" remote get-url origin 2>/dev/null | sed 's#//[^@]*@#//#' || echo 'xahau-hub')" \
    > "$tmp"

  # ── post-render assertions ───────────────────────────────────────────────
  grep -q '^\[node_seed\]' "$tmp"                  || die "$node: rendered config has no [node_seed]"
  grep -qE '^\s*admin = 127\.0\.0\.1\s*$' "$tmp"   || die "$node: admin is not pinned to 127.0.0.1 — refusing"
  awk '/^\[port_rpc_admin_local\]/{f=1;next} /^\[/{f=0} f && /ip *= *0\.0\.0\.0/{exit 1}' "$tmp" \
    || die "$node: admin RPC is bound to 0.0.0.0 — refusing. Admin must never leave localhost."
  grep -qE '^use_tx_tables|^\[use_tx_tables\]' "$tmp" || die "$node: [use_tx_tables] missing"
  grep -q "^online_delete=$N_ONLINE_DELETE$" "$tmp" || die "$node: online_delete did not render"
  grep -q "^advisory_delete=1$" "$tmp"              || die "$node: advisory_delete must be 1 (prune-guard.sh drives pruning)"

  mv "$tmp" "$dest/xahaud.cfg"; chmod 600 "$dest/xahaud.cfg"
  install -m 644 "$REPO_ROOT/config/validators.txt" "$dest/validators.txt"

  if [ "$PRINT" = 1 ]; then
    sed 's/^s[1-9A-HJ-NP-Za-km-z]\{20,\}$/<<REDACTED NODE SEED>>/' "$dest/xahaud.cfg"
  fi
  ok "$node ($V_ROLE): ledger_history=$lh online_delete=$N_ONLINE_DELETE node_size=$N_NODE_SIZE peers_max=$N_PEERS_MAX -> $dest/xahaud.cfg"
}

for n in "${NODES[@]}"; do render_one "$n"; done
info "rendered configs are mode 0600 and gitignored — they contain real seeds"
